
package calculator;

/**
 *
 * @author Fernando
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Calculator");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wallpaper = new javax.swing.JLabel();
        menu = new javax.swing.JToolBar();
        Standard = new javax.swing.JToggleButton();
        Scientific = new javax.swing.JToggleButton();
        BinToDec = new javax.swing.JToggleButton();
        HexToDec = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menu.setRollover(true);

        Standard.setText("Standard Calculator");
        Standard.setFocusable(false);
        Standard.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Standard.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Standard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StandardActionPerformed(evt);
            }
        });
        menu.add(Standard);

        Scientific.setText("Scientific calculator");
        Scientific.setFocusable(false);
        Scientific.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Scientific.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        menu.add(Scientific);

        BinToDec.setText("Bin to Dec");
        BinToDec.setFocusable(false);
        BinToDec.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BinToDec.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        menu.add(BinToDec);

        HexToDec.setText("Hex to Dec");
        HexToDec.setFocusable(false);
        HexToDec.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        HexToDec.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        menu.add(HexToDec);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(wallpaper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wallpaper, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StandardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StandardActionPerformed
        StandardCalc standard = new StandardCalc();
        standard.setVisible(Standard.isSelected());
    }//GEN-LAST:event_StandardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BinToDec;
    private javax.swing.JToggleButton HexToDec;
    private javax.swing.JToggleButton Scientific;
    private javax.swing.JToggleButton Standard;
    private javax.swing.JToolBar menu;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables
}
